#this function takes input opening and calling ranges and fills PIO solver with these options.
#p2 (calling) has ranges generated by functions in RangeCalculations
#p2 (calling) additionally will have bet sizes set by user data - options for personal hand data or global data.
#bet sizes for p1 are optimized over each flop (and/or the range of flops?) to maximize EV.

#more info in google sheet
